import { FaJava } from "react-icons/fa";
import {
  FaBrain,
  FaChartBar,
  FaFileAlt,
  FaGlobe,
  FaLayerGroup,
  FaLinkedin,
  FaServer,
} from "react-icons/fa";
import { HiMiniCpuChip } from "react-icons/hi2";
import {
  SiApachekafka,
  SiDocker,
  SiDjango,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGithub,
  SiHuggingface,
  SiJavascript,
  SiJsonwebtokens,
  SiKeras,
  SiMongodb,
  SiMysql,
  SiNeo4J,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiScikitlearn,
  SiTailwindcss,
  SiTensorflow,
  SiTwilio,
  SiTypescript,
  SiYolo,
} from "react-icons/si";

export const SITE_CONFIG = {
  title: "Vasuki G — AI & Data Science Enthusiast",
  author: "Vasuki G",
  description:
    "AI & Data Science student passionate about machine learning, full-stack development, and building innovative solutions.",
  siteLogo: "/logo.png",
  socialLinks: [
    {
      text: "Resume",
      href: "/Vasuki_G.docx",
      icon: FaFileAlt,
    },
    {
      text: "Github",
      href: "https://github.com/vasuki2756",
      icon: SiGithub,
    },
    {
      text: "LinkedIn",
      href: "https://linkedin.com/in/vasuki-g-0b31a9288",
      icon: FaLinkedin,
    },
  ],
  menuItems: [
    { label: "Resume", href: "/Vasuki_G.docx" },
    { label: "Experience", href: "#experience" },
    { label: "Projects", href: "#projects" },
    { label: "Contact", href: "#contact" },
  ],
  socialImage: "/assets/og.png",
  contact: {
    email: "mvmaki27@gmail.com",
    cal_link: "https://cal.com/vasuki-g",
  },
};

export const ABOUT_CONTENT = {
  name: "Vasuki G",
  location: "Sivakasi, Tamilnadu",
  phone: "+91-86103 67525",
  email: "mvmaki27@gmail.com",
  degree: "B.Tech in Artificial Intelligence & Data Science",
  institution: "Karunya Institute of Technology & Sciences",
  cgpa: "9.56/10",
  interests: [
    "Machine Learning",
    "Artificial Intelligence",
    "Cloud Computing",
    "Prompt Engineering",
  ],
  certifications: [
    "MongoDB Python Developer Path — MongoDB",
    "Building AI Agents with MongoDB — MongoDB",
    "AWS DynamoDB — Infosys Springboard",
    "Java Programming Fundamentals — Infosys",
    "Programming Essentials In Python — Cisco",
    "Microsoft Azure AI Fundamentals (AI-900) — Microsoft",
  ],
  summary:
    "Aspiring AI/ML Engineer with a 9.52 CGPA, multiple internships, and hands-on experience building generative AI apps, full-stack platforms, and real-time data pipelines. A fast learner who takes initiative, collaborates effectively, and turns complex problems into scalable solutions.",
};

export const SITE_CONTENT = {
  hero: {
    name: "Vasuki G",
    summary: "AI & Data Science Enthusiast | Full-Stack Developer",
    currentWork: "Software Development Intern at GMS SoftTeam Solutions",
    image: "/hero.png",
    stats: [
      { label: "CGPA", value: "9.56/10" },
      { label: "Projects Completed", value: "07+" },
    ],
  },
  skills: {
    languages: [
      { name: "Python", icon: SiPython },
      { name: "JavaScript", icon: SiJavascript },
      { name: "Java", icon: FaJava },
      { name: "SQL", icon: SiMysql },
      { name: "PHP", icon: SiPhp },
      "HTML",
      "CSS",
    ],
    libraries: [
      { name: "React", icon: SiReact },
      { name: "Tailwind CSS", icon: SiTailwindcss },
      { name: "Express.js", icon: SiExpress },
      { name: "JWT", icon: SiJsonwebtokens },
    ],
    frameworks: [
      { name: "FastAPI", icon: SiFastapi },
      { name: "Django", icon: SiDjango },
      { name: "Flask", icon: SiFlask },
    ],
    databases: [
      { name: "MongoDB", icon: SiMongodb },
      { name: "MySQL", icon: SiMysql },
      { name: "PostgreSQL", icon: SiPostgresql },
    ],
    tools: [
      { name: "Git/GitHub", icon: SiGithub },
      { name: "Docker", icon: SiDocker },
      { name: "Power BI", icon: FaChartBar },
      "Google Antigravity (AI IDE)",
      { name: "Hugging Face CLI", icon: SiHuggingface },
    ],
    hardware: [],
    platforms: [
      { name: "Hugging Face", icon: SiHuggingface },
      { name: "scikit-learn", icon: SiScikitlearn },
      { name: "Firebase", icon: SiFirebase },
    ],
  },
  experience: [
    {
      id: "gms-softteam",
      companyName: "GMS SoftTeam Solutions Pvt. Ltd.",
      companyLink: "#",
      companyLogo: "",
      positions: [
        {
          id: "gms-softteam-001",
          title: "Software Development Intern",
          employmentPeriod: "Jan 2026 — Present",
          employmentType: "Internship",
          icon: "code",
          description: `- Developing an internal web-based testing tool, enhancing features and system functionality.`,
          skills: [
            "React",
            "JavaScript",
            "Web Development",
            "System Design",
          ],
          isExpanded: true,
        },
      ],
      isCurrentEmployer: true,
    },
    {
      id: "inlignx",
      companyName: "INLIGNX Global Internship",
      companyLink: "#",
      companyLogo: "",
      positions: [
        {
          id: "inlignx-001",
          title: "Front-end Development Intern",
          employmentPeriod: "Jul 2025 — Aug 2025",
          employmentType: "Internship",
          icon: "code",
          description: `- Developed responsive React.js applications including a To-Do List and Expense Tracker with state management, filtering, and local storage integration.`,
          skills: [
            "React",
            "JavaScript",
            "State Management",
            "Responsive Design",
          ],
          isExpanded: false,
        },
      ],
      isCurrentEmployer: false,
    },
    {
      id: "aiimtech",
      companyName: "AIIMTECH Software Systems Pvt. Ltd.",
      companyLink: "#",
      companyLogo: "",
      positions: [
        {
          id: "aiimtech-001",
          title: "Web Development Intern",
          employmentPeriod: "Jun 2024 — Jul 2024",
          employmentType: "Internship",
          icon: "code",
          description: `- Assisted in developing responsive web applications using HTML, CSS, JavaScript, and PHP, improving UI consistency and usability.`,
          skills: [
            "HTML",
            "CSS",
            "JavaScript",
            "PHP",
            "Responsive Design",
          ],
          isExpanded: false,
        },
      ],
      isCurrentEmployer: false,
    },
    {
      id: "technical-tutor",
      companyName: "Unbiased Club & Skill Development Program",
      companyLink: "#",
      companyLogo: "",
      positions: [
        {
          id: "technical-tutor-001",
          title: "Technical Tutor",
          employmentPeriod: "Jul 2025 — Present",
          employmentType: "Part-time",
          icon: "education",
          description: `- Mentored junior students in programming fundamentals and problem-solving through structured sessions.`,
          skills: [
            "Mentorship",
            "Programming Fundamentals",
            "Problem Solving",
          ],
          isExpanded: false,
        },
      ],
      isCurrentEmployer: false,
    },
  ],
  education: [
    {
      name: "Karunya Institute of Technology & Sciences",
      location: "Coimbatore, Tamilnadu",
      position: "B.Tech in Artificial Intelligence & Data Science",
      start: "Nov 2021",
      end: "Expected May 2027",
      link: "https://karunya.edu/",
      logo: "https://karunya.edu/logo.png",
    },
    {
      name: "SHN Girl's Higher Secondary School",
      location: "Sivakasi, Tamilnadu",
      position: "Secondary and Higher Secondary",
      start: "Jun 2021",
      end: "May 2023",
      link: "#",
      logo: "",
    },
  ],
  categories: [
    { value: "all", label: "All", icon: FaLayerGroup },
    { value: "ai-ml", label: "AI/ML", icon: FaBrain },
    { value: "computer-vision", label: "Computer Vision", icon: HiMiniCpuChip },
    { value: "llm", label: "LLM", icon: FaBrain },
    { value: "full-stack", label: "Full-Stack", icon: FaGlobe },
    { value: "backend", label: "Backend", icon: FaServer },
    { value: "datapipe", label: "Data Pipeline", icon: FaChartBar },
  ],
  projects: [
    {
      name: "DrugTrace",
      description: "AI-powered drug repurposing platform using multi-agent architecture. Leverages knowledge graphs, literature search, and mechanistic hypothesis generation to identify candidate drugs. Won 3rd Prize at Cognizant Technoverse Hackathon 2026.",
      category: ["AI/ML", "LLM", "Backend"],
      image: "",
      url: "https://github.com/Danishprabhu04/Devtronix_Drug_Repurposing-",
      hosted_url: "https://github.com/Danishprabhu04/Devtronix_Drug_Repurposing-",
      technologies: [
        { name: "Python", icon: SiPython },
        { name: "FastAPI", icon: SiFastapi },
        { name: "Neo4j", icon: SiNeo4J },
        { name: "React", icon: SiReact },
        "AWS",
        { name: "Docker", icon: SiDocker },
      ],
    },
    {
      name: "Vehicle Detection for Gas Stations",
      description: "Production-grade vehicle detection system for gas stations using YOLOv8 + SAM2 segmentation. Features real-time license plate OCR (96% accuracy), multi-agent orchestration, and live React dashboard with WebSocket updates.",
      category: ["Computer Vision", "Full-Stack", "Backend"],
      image: "",
      url: "https://github.com/vasuki2756/vehicle_detection-for-gas-stations",
      hosted_url: "https://github.com/vasuki2756/vehicle_detection-for-gas-stations",
      technologies: [
        { name: "Python", icon: SiPython },
        { name: "FastAPI", icon: SiFastapi },
        { name: "YOLOv8", icon: SiYolo },
        { name: "React", icon: SiReact },
        { name: "Twilio", icon: SiTwilio },
        "SQLite",
      ],
    },
    {
      name: "SitePlanner",
      description: "AI-powered construction planning platform that converts raw task registers into realistic, feasible day-level execution plans. Uses predictive delay-risk scoring, constraint-based scheduling, and feedback-driven learning.",
      category: ["AI/ML", "Full-Stack", "Backend"],
      image: "",
      url: "https://github.com/vasuki2756/site-planner",
      hosted_url: "https://ai-site-planner.vercel.app",
      technologies: [
        { name: "React", icon: SiReact },
        { name: "FastAPI", icon: SiFastapi },
        { name: "PostgreSQL", icon: SiPostgresql },
        { name: "Firebase", icon: SiFirebase },
        { name: "scikit-learn", icon: SiScikitlearn },
        { name: "TypeScript", icon: SiTypescript },
      ],
    },
    {
      name: "Food Calorie Estimator",
      description: "AI-powered web app that estimates calories and nutritional information from food photos. Combines TensorFlow deep learning (101-class food classifier), Google Gemini for intelligent analysis, and real-time Edamam nutrition API.",
      category: ["AI/ML", "Computer Vision", "Full-Stack"],
      image: "",
      url: "https://github.com/vasuki2756/Food-Calorie-Estimater",
      hosted_url: "https://github.com/vasuki2756/Food-Calorie-Estimater",
      technologies: [
        { name: "Python", icon: SiPython },
        { name: "FastAPI", icon: SiFastapi },
        { name: "TensorFlow", icon: SiTensorflow },
        { name: "Keras", icon: SiKeras },
        "SQLite",
      ],
    },
    {
      name: "EventNest",
      description: "Full-stack event management platform with Express + MongoDB backend, JWT authentication, and React frontend. Features event creation, discovery, RSVP, user profiles, and a modern dark design system with theme context.",
      category: ["Full-Stack", "Backend"],
      image: "",
      url: "https://github.com/vasuki2756/EventNest",
      hosted_url: "https://eventnest.vercel.app",
      technologies: [
        { name: "React", icon: SiReact },
        { name: "Express.js", icon: SiExpress },
        { name: "MongoDB", icon: SiMongodb },
        { name: "JWT", icon: SiJsonwebtokens },
      ],
    },
    {
      name: "AI Hiring Simulator",
      description: "AI-powered hiring readiness platform using Groq's Llama 3.3 LLM. Analyzes resumes, detects skills gaps, generates context-aware interview questions, and evaluates answers with detailed scoring and feedback.",
      category: ["AI/ML", "LLM", "Full-Stack"],
      image: "",
      url: "https://github.com/vasuki2756/Formal-candidate-analysis-and-interview-workflow",
      hosted_url: "https://github.com/vasuki2756/Formal-candidate-analysis-and-interview-workflow",
      technologies: [
        { name: "Python", icon: SiPython },
        { name: "FastAPI", icon: SiFastapi },
        { name: "React", icon: SiReact },
        { name: "TypeScript", icon: SiTypescript },
        { name: "Groq API", icon: SiHuggingface },
      ],
    },
    {
      name: "AQI Pipeline",
      description: "Production-ready real-time data pipeline for Air Quality Index monitoring across Indian cities. Demonstrates Lambda Architecture with Apache Kafka streaming, MySQL persistence, and Power BI visualization with Docker containerization.",
      category: "Data Pipeline",
      image: "",
      url: "https://github.com/vasuki2756/AQI-Pipeline-Kafka-MySQL-PowerBI",
      hosted_url: "https://github.com/vasuki2756/AQI-Pipeline-Kafka-MySQL-PowerBI",
      technologies: [
        { name: "Python", icon: SiPython },
        { name: "Apache Kafka", icon: SiApachekafka },
        { name: "MySQL", icon: SiMysql },
        { name: "Power BI", icon: FaChartBar },
        { name: "Docker", icon: SiDocker },
      ],
    },
  ],
  testimonials: [
    {
      id: 0,
      testimonial:
        "Vasuki demonstrated strong technical skills and a great ability to learn quickly. Her work on our web applications was impressive and she consistently delivered high-quality results.",
      by: "Team Lead, GMS SoftTeam Solutions",
    },
    {
      id: 1,
      testimonial:
        "She has a natural talent for breaking down complex problems and finding elegant solutions. A dedicated and passionate developer.",
      by: "Mentor, INLIGNX Global Internship",
    },
    {
      id: 2,
      testimonial:
        "Vasuki's ability to grasp new concepts and apply them effectively is remarkable. She was a valuable contributor to our projects.",
      by: "Project Supervisor, AIIMTECH",
    },
    {
      id: 3,
      testimonial:
        "As a technical tutor, she was patient, knowledgeable, and truly invested in helping others succeed.",
      by: "Student, Skill Development Program",
    },
    {
      id: 4,
      testimonial: "An exceptional problem solver with a keen eye for detail and a passion for innovation.",
      by: "Peer, Karunya Institute of Technology",
    },
  ],
};
